### ISSUE TITLE
NPM Installs for font awesome icons (and rescourses to use them)

### ISSUE THREAD

**Issue by markbrew3** [Mestany2/Team-YouTube#26]
npm i --save @fortawesome/free-solid-svg-icons
npm i --save @fortawesome/free-regular-svg-icons
npm i --save @fortawesome/fontawesome-svg-core
https://fontawesome.com/docs/web/use-with/react/add-icons
https://www.youtube.com/watch?v=L4CK3j72SfM

**Comment by SteveCButler** [comment]
team members installed
